import { motion } from "framer-motion";
import { Section } from "@/components/Section";
import { ShimmerOverlay } from "@/components/Shimmer";
import { sectionMount, staggerContainer, staggerItem } from "@/lib/motionVariants";
import type { AIAnalysis, CameraSettings } from "@/types/analysis";

interface AICritiqueDashboardProps {
  ai: AIAnalysis | null;
  loading?: boolean;
  error?: string | null;
  /** Stagger offset (seconds) so this section can cascade in after siblings. */
  delay?: number;
}

const SECTION_DESCRIPTION =
  "A photographer's read on the shot — scene, light, settings, and how to recreate it. Generated by Claude, grounded in the measurements above.";

export function AICritiqueDashboard({
  ai,
  loading = false,
  error = null,
  delay = 0,
}: AICritiqueDashboardProps) {
  return (
    <motion.div {...sectionMount(delay)}>
      <Section
        number="03"
        title="AI CRITIQUE"
        description={SECTION_DESCRIPTION}
        action={
          loading ? (
            <span className="animate-pulse rounded-sm bg-blue-400/10 px-3 py-1 font-mono text-xs uppercase tracking-widest text-blue-400">
              Thinking…
            </span>
          ) : undefined
        }
      >
        {loading ? (
          <CritiqueSkeleton />
        ) : error ? (
          <Banner tone="error">{error}</Banner>
        ) : !ai ? (
          <p className="text-sm text-muted">
            Run the analysis to generate an AI critique.
          </p>
        ) : !ai.available ? (
          <Banner tone="muted">
            {ai.reason ?? "AI analysis is unavailable."}
          </Banner>
        ) : (
          <CritiqueContent ai={ai} />
        )}
      </Section>
    </motion.div>
  );
}

function CritiqueContent({ ai }: { ai: AIAnalysis }) {
  return (
    <div className="space-y-6">
      {ai.scene && (ai.scene.summary || ai.scene.tags.length > 0) && (
        <div>
          <h3 className="mb-2 font-mono text-xs uppercase tracking-widest text-dim">
            Scene
          </h3>
          {ai.scene.summary && (
            <p className="text-base leading-relaxed text-[#999999]">
              {ai.scene.summary}
            </p>
          )}
          <div className="mt-3 flex flex-wrap items-center gap-2">
            {ai.scene.setting && (
              <span className="rounded-sm bg-accent px-2.5 py-1 font-mono text-xs text-bg">
                {ai.scene.setting}
              </span>
            )}
            {ai.scene.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-sm border border-border px-2.5 py-1 font-mono text-xs text-muted"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      )}

      <motion.div
        variants={staggerContainer}
        initial="hidden"
        animate="show"
        className="grid gap-4 lg:grid-cols-2"
      >
        {ai.subject && (ai.subject.primary || ai.subject.description) && (
          <motion.div variants={staggerItem}>
            <InfoCard title="Subject">
              {ai.subject.primary && (
                <p className="font-medium text-ink">{ai.subject.primary}</p>
              )}
              {ai.subject.description && (
                <p className="mt-1 text-sm text-muted">
                  {ai.subject.description}
                </p>
              )}
            </InfoCard>
          </motion.div>
        )}

        {ai.lighting && (ai.lighting.summary || ai.lighting.direction) && (
          <motion.div variants={staggerItem}>
            <InfoCard title="Lighting">
              {ai.lighting.summary && (
                <p className="text-sm text-[#999999]">{ai.lighting.summary}</p>
              )}
              <div className="mt-2 flex flex-wrap gap-2">
                <Chip label="Direction" value={ai.lighting.direction} />
                <Chip label="Quality" value={ai.lighting.quality} />
                <Chip label="Time" value={ai.lighting.time_of_day} />
              </div>
            </InfoCard>
          </motion.div>
        )}
      </motion.div>

      {ai.camera_settings && <CameraSettingsCard settings={ai.camera_settings} />}

      {ai.composition_critique && (
        <motion.div
          variants={staggerContainer}
          initial="hidden"
          animate="show"
          className="grid gap-4 lg:grid-cols-2"
        >
          {ai.composition_critique.strengths.length > 0 && (
            <motion.div variants={staggerItem}>
              <InfoCard title="What works">
                <BulletList items={ai.composition_critique.strengths} tone="good" />
              </InfoCard>
            </motion.div>
          )}
          {ai.composition_critique.improvements.length > 0 && (
            <motion.div variants={staggerItem}>
              <InfoCard title="What to improve">
                <BulletList
                  items={ai.composition_critique.improvements}
                  tone="suggest"
                />
              </InfoCard>
            </motion.div>
          )}
          {ai.composition_critique.overall && (
            <div className="lg:col-span-2">
              <p className="text-sm leading-relaxed text-muted">
                {ai.composition_critique.overall}
              </p>
            </div>
          )}
        </motion.div>
      )}

      {ai.recreation_guide.length > 0 && (
        <div>
          <h3 className="mb-3 font-mono text-xs uppercase tracking-widest text-dim">
            Recreation guide
          </h3>
          <ol className="space-y-2">
            {ai.recreation_guide.map((step, i) => (
              <li key={i} className="flex gap-3 text-sm text-[#999999]">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-sm bg-accent font-mono text-xs font-semibold text-bg">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <span className="leading-relaxed">{step}</span>
              </li>
            ))}
          </ol>
        </div>
      )}
    </div>
  );
}

function CameraSettingsCard({ settings }: { settings: CameraSettings }) {
  const items: Array<[string, string | null]> = [
    ["Aperture", settings.aperture],
    ["Shutter", settings.shutter_speed],
    ["ISO", settings.iso],
    ["Focal length", settings.focal_length],
  ];
  const hasAny = items.some(([, v]) => v);
  if (!hasAny && !settings.reasoning) return null;

  return (
    <InfoCard title="Camera settings">
      <div className="mb-2 flex items-center gap-2">
        <span className="rounded-sm border border-border px-2 py-0.5 font-mono text-xs uppercase tracking-wide text-muted">
          {settings.from_exif ? "From EXIF" : "Estimated"}
        </span>
      </div>
      {hasAny && (
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          {items.map(([label, value]) => (
            <div
              key={label}
              className="border border-border bg-bg px-3 py-2"
            >
              <div className="font-mono text-xs text-muted">{label}</div>
              <div className="mt-0.5 font-mono text-sm text-ink">
                {value ?? "—"}
              </div>
            </div>
          ))}
        </div>
      )}
      {settings.reasoning && (
        <p className="mt-3 text-sm leading-relaxed text-muted">
          {settings.reasoning}
        </p>
      )}
    </InfoCard>
  );
}

function InfoCard({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded border border-border bg-surface p-5">
      <h3 className="mb-2 font-mono text-xs uppercase tracking-widest text-dim">
        {title}
      </h3>
      {children}
    </div>
  );
}

function Chip({ label, value }: { label: string; value: string | null }) {
  if (!value) return null;
  return (
    <span className="rounded-sm bg-bg px-2.5 py-1 font-mono text-xs text-muted">
      <span className="text-muted">{label}:</span> {value}
    </span>
  );
}

function BulletList({
  items,
  tone,
}: {
  items: string[];
  tone: "good" | "suggest";
}) {
  const textColor = tone === "good" ? "text-[#cccccc]" : "text-[#999999]";
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className={`flex gap-2.5 text-sm ${textColor}`}>
          <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-heading" />
          <span className="leading-relaxed">{item}</span>
        </li>
      ))}
    </ul>
  );
}

function Banner({
  tone,
  children,
}: {
  tone: "error" | "muted";
  children: React.ReactNode;
}) {
  const styles =
    tone === "error"
      ? "border-red-500/40 bg-red-500/10 text-red-300"
      : "border-border bg-surface text-muted";
  return (
    <div className={`border px-4 py-3 font-mono text-sm ${styles}`}>
      {children}
    </div>
  );
}

function CritiqueSkeleton() {
  return (
    <div className="space-y-4">
      <div className="relative h-5 w-3/4 overflow-hidden bg-border">
        <ShimmerOverlay />
      </div>
      <div className="flex gap-2">
        <div className="relative h-6 w-20 overflow-hidden rounded-sm bg-border">
          <ShimmerOverlay />
        </div>
        <div className="relative h-6 w-16 overflow-hidden rounded-sm bg-border">
          <ShimmerOverlay />
        </div>
        <div className="relative h-6 w-24 overflow-hidden rounded-sm bg-border">
          <ShimmerOverlay />
        </div>
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <div className="relative h-28 overflow-hidden bg-surface">
          <ShimmerOverlay />
        </div>
        <div className="relative h-28 overflow-hidden bg-surface">
          <ShimmerOverlay />
        </div>
      </div>
      <div className="relative h-24 overflow-hidden bg-surface">
        <ShimmerOverlay />
      </div>
    </div>
  );
}
