import { motion } from "framer-motion";
import { Section } from "@/components/Section";
import { ShimmerOverlay } from "@/components/Shimmer";
import { fadeUpIn, staggerContainer, staggerItem } from "@/lib/motionVariants";
import type { AIAnalysis, CameraSettings, FujifilmRecipe } from "@/types/analysis";

interface AICritiqueDashboardProps {
  ai: AIAnalysis | null;
  loading?: boolean;
  error?: string | null;
}

const SECTION_DESCRIPTION =
  "A photographer's read on the shot — scene, light, settings, and how to recreate it. Generated by Claude, grounded in the measurements above.";

export function AICritiqueDashboard({
  ai,
  loading = false,
  error = null,
}: AICritiqueDashboardProps) {
  return (
    <motion.div {...fadeUpIn(0.3)}>
      <Section
        title="AI critique"
        description={SECTION_DESCRIPTION}
        action={
          loading ? (
            <span className="animate-pulse rounded-full bg-violet-500/15 px-3 py-1 text-xs font-medium text-violet-300">
              Thinking…
            </span>
          ) : undefined
        }
      >
        {loading ? (
          <CritiqueSkeleton />
        ) : error ? (
          <Banner tone="error">{error}</Banner>
        ) : !ai ? (
          <p className="text-sm text-neutral-500">
            Run the analysis to generate an AI critique.
          </p>
        ) : !ai.available ? (
          <Banner tone="muted">
            {ai.reason ?? "AI analysis is unavailable."}
          </Banner>
        ) : (
          <CritiqueContent ai={ai} />
        )}
      </Section>
    </motion.div>
  );
}

function CritiqueContent({ ai }: { ai: AIAnalysis }) {
  return (
    <div className="space-y-6">
      {ai.scene && (ai.scene.summary || ai.scene.tags.length > 0) && (
        <div>
          {ai.scene.summary && (
            <p className="text-base leading-relaxed text-neutral-200">
              {ai.scene.summary}
            </p>
          )}
          <div className="mt-3 flex flex-wrap items-center gap-2">
            {ai.scene.setting && (
              <span className="rounded-lg bg-neutral-800 px-2.5 py-1 text-xs text-neutral-300">
                {ai.scene.setting}
              </span>
            )}
            {ai.scene.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-full border border-neutral-700 px-2.5 py-1 text-xs text-neutral-400"
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      )}

      <motion.div
        variants={staggerContainer}
        initial="hidden"
        animate="show"
        className="grid gap-4 lg:grid-cols-2"
      >
        {ai.subject && (ai.subject.primary || ai.subject.description) && (
          <motion.div variants={staggerItem}>
            <InfoCard title="Subject">
              {ai.subject.primary && (
                <p className="font-medium text-neutral-200">{ai.subject.primary}</p>
              )}
              {ai.subject.description && (
                <p className="mt-1 text-sm text-neutral-400">
                  {ai.subject.description}
                </p>
              )}
            </InfoCard>
          </motion.div>
        )}

        {ai.lighting && (ai.lighting.summary || ai.lighting.direction) && (
          <motion.div variants={staggerItem}>
            <InfoCard title="Lighting">
              {ai.lighting.summary && (
                <p className="text-sm text-neutral-300">{ai.lighting.summary}</p>
              )}
              <div className="mt-2 flex flex-wrap gap-2">
                <Chip label="Direction" value={ai.lighting.direction} />
                <Chip label="Quality" value={ai.lighting.quality} />
                <Chip label="Time" value={ai.lighting.time_of_day} />
              </div>
            </InfoCard>
          </motion.div>
        )}
      </motion.div>

      {ai.camera_settings && <CameraSettingsCard settings={ai.camera_settings} />}

      {ai.composition_critique && (
        <motion.div
          variants={staggerContainer}
          initial="hidden"
          animate="show"
          className="grid gap-4 lg:grid-cols-2"
        >
          {ai.composition_critique.strengths.length > 0 && (
            <motion.div variants={staggerItem}>
              <InfoCard title="What works">
                <BulletList items={ai.composition_critique.strengths} tone="good" />
              </InfoCard>
            </motion.div>
          )}
          {ai.composition_critique.improvements.length > 0 && (
            <motion.div variants={staggerItem}>
              <InfoCard title="What to improve">
                <BulletList
                  items={ai.composition_critique.improvements}
                  tone="suggest"
                />
              </InfoCard>
            </motion.div>
          )}
          {ai.composition_critique.overall && (
            <div className="lg:col-span-2">
              <p className="text-sm leading-relaxed text-neutral-300">
                {ai.composition_critique.overall}
              </p>
            </div>
          )}
        </motion.div>
      )}

      {ai.recreation_guide.length > 0 && (
        <div>
          <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide text-neutral-400">
            Recreation guide
          </h3>
          <ol className="space-y-2">
            {ai.recreation_guide.map((step, i) => (
              <li key={i} className="flex gap-3 text-sm text-neutral-300">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-violet-500/15 text-xs font-semibold text-violet-300">
                  {i + 1}
                </span>
                <span className="leading-relaxed">{step}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      {ai.fujifilm_recipe?.applicable === true && (
        <FujifilmRecipeCard recipe={ai.fujifilm_recipe} />
      )}
    </div>
  );
}

function CameraSettingsCard({ settings }: { settings: CameraSettings }) {
  const items: Array<[string, string | null]> = [
    ["Aperture", settings.aperture],
    ["Shutter", settings.shutter_speed],
    ["ISO", settings.iso],
    ["Focal length", settings.focal_length],
  ];
  const hasAny = items.some(([, v]) => v);
  if (!hasAny && !settings.reasoning) return null;

  return (
    <InfoCard title="Camera settings">
      <div className="mb-2 flex items-center gap-2">
        <span
          className={`rounded-full px-2 py-0.5 text-xs font-medium ${
            settings.from_exif
              ? "bg-emerald-500/15 text-emerald-300"
              : "bg-amber-500/15 text-amber-300"
          }`}
        >
          {settings.from_exif ? "From EXIF" : "Estimated"}
        </span>
      </div>
      {hasAny && (
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          {items.map(([label, value]) => (
            <div
              key={label}
              className="rounded-lg border border-neutral-800 bg-neutral-900/50 px-3 py-2"
            >
              <div className="text-xs text-neutral-500">{label}</div>
              <div className="mt-0.5 font-mono text-sm text-neutral-200">
                {value ?? "—"}
              </div>
            </div>
          ))}
        </div>
      )}
      {settings.reasoning && (
        <p className="mt-3 text-sm leading-relaxed text-neutral-400">
          {settings.reasoning}
        </p>
      )}
    </InfoCard>
  );
}

function FujifilmRecipeCard({ recipe }: { recipe: FujifilmRecipe }) {
  const s = recipe.settings;
  const textRows: Array<[string, string | null | undefined]> = [
    ["Grain", s?.grain],
    ["Color Chrome Effect", s?.color_chrome_effect],
    ["White Balance", s?.white_balance],
  ];
  const numRows: Array<[string, number | null | undefined]> = [
    ["Highlights", s?.highlights],
    ["Shadows", s?.shadows],
    ["Color", s?.color],
    ["Sharpness", s?.sharpness],
    ["Noise Reduction", s?.noise_reduction],
  ];

  return (
    <InfoCard title="Fujifilm Recipe">
      {recipe.film_simulation && (
        <div className="mb-3">
          <span className="rounded-full bg-emerald-500/15 px-2.5 py-0.5 text-xs font-medium text-emerald-300">
            {recipe.film_simulation}
          </span>
        </div>
      )}
      <div className="space-y-1.5">
        {textRows.map(([label, value]) =>
          value ? (
            <div
              key={label}
              className="flex items-center justify-between gap-3 text-sm"
            >
              <span className="text-neutral-500">{label}</span>
              <span className="text-neutral-200">{value}</span>
            </div>
          ) : null,
        )}
        {numRows.map(([label, value]) =>
          value != null ? (
            <div
              key={label}
              className="flex items-center justify-between gap-3 text-sm"
            >
              <span className="text-neutral-500">{label}</span>
              <span className="font-mono text-neutral-200">
                {value > 0 ? `+${value}` : `${value}`}
              </span>
            </div>
          ) : null,
        )}
      </div>
      {recipe.reasoning && (
        <p className="mt-3 text-sm italic leading-relaxed text-neutral-400">
          {recipe.reasoning}
        </p>
      )}
    </InfoCard>
  );
}

function InfoCard({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-xl border border-neutral-800 bg-neutral-900/40 p-4">
      <h3 className="mb-2 text-sm font-semibold uppercase tracking-wide text-neutral-400">
        {title}
      </h3>
      {children}
    </div>
  );
}

function Chip({ label, value }: { label: string; value: string | null }) {
  if (!value) return null;
  return (
    <span className="rounded-lg bg-neutral-800 px-2.5 py-1 text-xs text-neutral-300">
      <span className="text-neutral-500">{label}:</span> {value}
    </span>
  );
}

function BulletList({
  items,
  tone,
}: {
  items: string[];
  tone: "good" | "suggest";
}) {
  const dot = tone === "good" ? "bg-emerald-400" : "bg-amber-400";
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2.5 text-sm text-neutral-300">
          <span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
          <span className="leading-relaxed">{item}</span>
        </li>
      ))}
    </ul>
  );
}

function Banner({
  tone,
  children,
}: {
  tone: "error" | "muted";
  children: React.ReactNode;
}) {
  const styles =
    tone === "error"
      ? "border-red-500/40 bg-red-500/10 text-red-300"
      : "border-neutral-700 bg-neutral-800/40 text-neutral-400";
  return (
    <div className={`rounded-xl border px-4 py-3 text-sm ${styles}`}>
      {children}
    </div>
  );
}

function CritiqueSkeleton() {
  return (
    <div className="space-y-4">
      <div className="relative h-5 w-3/4 overflow-hidden rounded bg-neutral-800">
        <ShimmerOverlay />
      </div>
      <div className="flex gap-2">
        <div className="relative h-6 w-20 overflow-hidden rounded-full bg-neutral-800">
          <ShimmerOverlay />
        </div>
        <div className="relative h-6 w-16 overflow-hidden rounded-full bg-neutral-800">
          <ShimmerOverlay />
        </div>
        <div className="relative h-6 w-24 overflow-hidden rounded-full bg-neutral-800">
          <ShimmerOverlay />
        </div>
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <div className="relative h-28 overflow-hidden rounded-xl bg-neutral-800/50">
          <ShimmerOverlay />
        </div>
        <div className="relative h-28 overflow-hidden rounded-xl bg-neutral-800/50">
          <ShimmerOverlay />
        </div>
      </div>
      <div className="relative h-24 overflow-hidden rounded-xl bg-neutral-800/50">
        <ShimmerOverlay />
      </div>
    </div>
  );
}
